# Generated by Codex on 2025-?? adapting Odoo-like sequences

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=32)),
                ('descricao', models.CharField(blank=True, max_length=128)),
                ('prefixo', models.CharField(blank=True, max_length=16)),
                ('sufixo', models.CharField(blank=True, max_length=16)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
                ('incremento', models.PositiveSmallIntegerField(default=1)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencias', to='core.loja')),
            ],
            options={
                'ordering': ('codigo', 'loja__nome'),
            },
        ),
        migrations.AddConstraint(
            model_name='sequenciadocumento',
            constraint=models.UniqueConstraint(fields=('loja', 'codigo'), name='uniq_sequencia_documento_loja_codigo'),
        ),
    ]
