# Generated by Django 5.2.6 on 2025-09-30 13:27

from django.db import migrations

def create_initial_payment_methods(apps, schema_editor):
    FormaPagamento = apps.get_model('core', 'FormaPagamento')
    formas_pagamento = [
        {'nome': 'Dinheiro', 'tipo': 'DINHEIRO'},
        {'nome': 'Cartão de Débito', 'tipo': 'DEBITO'},
        {'nome': 'Cartão de Crédito', 'tipo': 'CREDITO'},
        {'nome': 'PIX', 'tipo': 'PIX'},
        {'nome': 'Transferência', 'tipo': 'TRANSFERENCIA'},
    ]

    for forma in formas_pagamento:
        FormaPagamento.objects.get_or_create(
            nome=forma['nome'],
            defaults={'tipo': forma['tipo'], 'ativo': True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequenciadocumento'),
    ]

    operations = [
        migrations.RunPython(create_initial_payment_methods),
    ]