# Generated by Django 5.2.6 on 2025-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contatos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_medio_entrega_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
