# Generated by Django 5.2.6 on 2025-09-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmitenteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serie', models.PositiveSmallIntegerField(default=1)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
                ('ambiente', models.CharField(choices=[('HOMOLOG', 'Homologação'), ('PROD', 'Produção')], default='HOMOLOG', max_length=8)),
                ('regime_tributario', models.CharField(blank=True, max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20)),
                ('certificado_nome', models.CharField(blank=True, max_length=255)),
                ('certificado_senha', models.CharField(blank=True, max_length=255)),
                ('certificado_arquivo_b64', models.TextField(blank=True, help_text='Conteúdo base64 do certificado A1 (.pfx)')),
                ('csc_id', models.CharField(blank=True, help_text='ID do CSC/NFC-e se aplicável', max_length=40)),
                ('csc_token', models.CharField(blank=True, max_length=40)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_nfe', to='core.loja')),
            ],
            options={
                'verbose_name': 'Configuração NF-e',
                'verbose_name_plural': 'Configurações NF-e',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.PositiveSmallIntegerField(default=1)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO', 'Em processamento'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('motivo_status', models.TextField(blank=True)),
                ('xml_assinado', models.TextField(blank=True)),
                ('xml_autorizado', models.TextField(blank=True)),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=60)),
                ('dh_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('ambiente', models.CharField(choices=[('HOMOLOG', 'Homologação'), ('PROD', 'Produção')], max_length=8)),
                ('total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('total_notafiscal', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('impostos_totais', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('dados_extra', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='nfe.emitenteconfig')),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_fiscal', to='sales.venda')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('CARTA_CORRECAO', 'Carta de Correção')], max_length=20)),
                ('justificativa', models.TextField()),
                ('protocolo', models.CharField(blank=True, max_length=60)),
                ('xml_evento', models.TextField(blank=True)),
                ('processamento', models.JSONField(blank=True, default=dict)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='nfe.notafiscal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto_nome', models.CharField(max_length=255)),
                ('produto_sku', models.CharField(blank=True, max_length=60)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=13)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=13)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('aliquota_icms', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('aliquota_ipi', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('aliquota_pis', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('aliquota_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('dados_impostos', models.JSONField(blank=True, default=dict)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nfe.notafiscal')),
            ],
            options={
                'verbose_name': 'Item da nota',
                'verbose_name_plural': 'Itens da nota',
                'ordering': ('id',),
            },
        ),
    ]
