# Generated by Django 5.0 on 2025-10-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                ("endereco", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Limite de Crédito",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="venda",
            name="data_vencimento",
            field=models.DateField(
                blank=True,
                help_text="Para vendas fiado",
                null=True,
                verbose_name="Data Vencimento",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="status_pagamento",
            field=models.CharField(
                choices=[("PAGO", "Pago"), ("PENDENTE", "Pendente")],
                default="PAGO",
                max_length=20,
                verbose_name="Status Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("DEBITO", "Débito"),
                    ("CREDITO", "Crédito"),
                    ("PIX", "PIX"),
                    ("FIADO", "Fiado"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
