# Generated by Django 5.0 on 2025-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adiciona índices compostos para otimizar queries frequentes.

    Baseado na análise de endpoints mais usados:
    - Dashboard: queries em Venda por status/pagamento/data
    - Contas a receber: vendas pendentes por cliente
    - Produtos: buscas por estoque e validade
    - ItemVenda: agregações por produto/venda
    """

    dependencies = [
        ('core', '0006_produto_data_validade_alter_cliente_limite_credito_and_more'),
    ]

    operations = [
        # VENDA - Queries mais frequentes no dashboard e contas a receber
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(
                fields=['status', 'status_pagamento', '-created_at'],
                name='venda_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(
                fields=['status', '-created_at'],
                name='venda_status_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(
                fields=['cliente', 'status_pagamento', 'data_vencimento'],
                name='venda_cliente_pag_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(
                fields=['forma_pagamento', 'status', '-created_at'],
                name='venda_forma_pag_idx'
            ),
        ),

        # ITEMVENDA - Agregações e relatórios
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(
                fields=['venda', 'produto'],
                name='itemvenda_vp_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(
                fields=['produto'],
                name='itemvenda_produto_idx'
            ),
        ),

        # PRODUTO - Alertas de estoque e validade
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(
                fields=['ativo', 'estoque'],
                name='produto_ativo_estoque_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(
                fields=['ativo', 'data_validade'],
                name='produto_validade_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(
                fields=['categoria', 'ativo'],
                name='produto_categoria_idx'
            ),
        ),

        # CLIENTE - Busca e relacionamentos
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(
                fields=['ativo', 'nome'],
                name='cliente_ativo_nome_idx'
            ),
        ),

        # CAIXA - Status e data
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(
                fields=['status', '-data_abertura'],
                name='caixa_status_idx'
            ),
        ),
    ]
