# Generated by Django 5.0 on 2025-10-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adiciona_fornecedor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fornecedor',
            new_name='core_fornec_ativo_0c3f83_idx',
            old_name='core_fornec_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='fornecedor',
            new_name='core_fornec_nome_3185fc_idx',
            old_name='core_fornec_nome_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='core_lote_produto_3b788b_idx',
            old_name='core_lote_produto_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='core_lote_data_va_4b9431_idx',
            old_name='core_lote_data_validade_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='core_lote_numero__00aeeb_idx',
            old_name='core_lote_numero_lote_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='core_lote_produto_508b05_idx',
            old_name='core_lote_produto_validade_ativo_idx',
        ),
    ]
