# Generated by Django 5.0 on 2025-10-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_fornec_ativo_idx_core_fornec_ativo_0c3f83_idx_and_more'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixas', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='lote',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_caixa', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='fiscal.empresa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='fiscal.empresa'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['empresa', '-created_at'], name='alerta_empresa_idx'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['empresa', 'status', '-data_abertura'], name='caixa_empresa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'ativo'], name='core_client_empresa_fd4856_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'ativo'], name='core_fornec_empresa_9ef407_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['empresa', 'ativo'], name='lote_empresa_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['empresa', '-created_at'], name='mov_caixa_empresa_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'ativo'], name='produto_empresa_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', '-created_at'], name='venda_empresa_created_idx'),
        ),
    ]
