# Generated by Django 5.0 on 2025-10-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alerta_empresa_caixa_empresa_categoria_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="conteudo_unidade",
            field=models.CharField(
                blank=True,
                help_text="Unidade do conteúdo (ex.: L, ml, g)",
                max_length=10,
                verbose_name="Unidade do Conteúdo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="conteudo_valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade numérica do conteúdo (ex.: 2.0)",
                max_digits=8,
                null=True,
                verbose_name="Conteúdo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="marca",
            field=models.CharField(blank=True, max_length=120, verbose_name="Marca"),
        ),
    ]
