# Generated by Django 5.0 on 2025-10-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_produto_conteudo_unidade_produto_conteudo_valor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="core.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
    ]
