# Generated by Django 5.0 on 2025-10-23 06:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_produto_fornecedor_alter_alerta_tipo"),
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioSessao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("responsavel", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="fiscal.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventário",
                "verbose_name_plural": "Inventários",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.CreateModel(
            name="InventarioItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_barras", models.CharField(blank=True, max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200)),
                (
                    "quantidade_sistema",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "quantidade_contada",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "custo_informado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("validade_informada", models.DateField(blank=True, null=True)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventarios",
                        to="core.produto",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.inventariosessao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Inventário",
                "verbose_name_plural": "Itens de Inventário",
                "ordering": ["descricao"],
            },
        ),
    ]
