# Generated by Django 5.0 on 2025-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_alerta_tipo_inventariosessao_inventarioitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LIMITE_CREDITO", "Limite de Crédito"),
                    ("PRODUTO_VENCENDO", "Produto Vencendo"),
                    ("PRODUTO_VENCIDO", "Produto Vencido"),
                    ("ESTOQUE_BAIXO", "Estoque Baixo"),
                    ("ESTOQUE_ZERADO", "Estoque Zerado"),
                    ("PRODUTO_SEM_PRECO", "Produto sem preço"),
                    ("CONTA_VENCIDA", "Conta Vencida"),
                    ("DIFERENCA_CAIXA", "Diferença de Caixa"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
