# Generated by Django 5.0 on 2025-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_categoria_nome_unique_add_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="validade_dias_padrao",
            field=models.IntegerField(
                blank=True,
                help_text="Dias de validade padrão para lotes desta categoria. Ex: 180 para refrigerantes",
                null=True,
                verbose_name="Validade Padrão (dias)",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="conferido",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o lote foi conferido fisicamente",
                verbose_name="Conferido",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="conferido_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora da conferência",
                null=True,
                verbose_name="Conferido em",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="validade_estimada",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a data de validade foi calculada automaticamente (precisa conferir)",
                verbose_name="Validade Estimada",
            ),
        ),
    ]
