# Generated by Django 5.0 on 2025-10-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_caixa_detalhamento_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='core.lote', verbose_name='Lote'),
        ),
    ]
