# Generated by Django 5.0 on 2025-10-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_inventarioitem_lote"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventarioitem",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventario_itens",
                to="core.categoria",
            ),
        ),
        migrations.AddField(
            model_name="inventarioitem",
            name="conteudo_unidade",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="inventarioitem",
            name="conteudo_valor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventarioitem",
            name="marca",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
