# Generated by Codex para alinhar PDV ao Odoo

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequenciadocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoPDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=16)),
                ('aberta_em', models.DateTimeField(default=timezone.now)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('saldo_fechamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_pdv', to='core.loja')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_pdv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='sales.sessaopdv'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
