# Generated by Django 5.2.6 on 2025-09-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_melhorias_controle_caixa'),
        ('sales', '0002_sessaopdv'),
    ]

    operations = [
    ]
